---
name: eliud_core_helpers
description: Eliud core helpers is the core helpers package. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_core_helpers
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  intl: ^0.19.0                                                                                      # ANDROID IOS LINUX MACOS WEB WINDOWS
  cloud_firestore: ^4.13.5                                                                           # ANDROID IOS       MACOS WEB WINDOWS
  uuid: ^4.2.1                                                                                       # ANDROID IOS LINUX MACOS WEB WINDOWS

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
