---
name: eliud_core_helpers
description: Eliud core helpers is the core helpers package. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_core_helpers
version: 1.3.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  intl: ^0.19.0
  cloud_firestore: ^5.4.3
  uuid: ^4.5.1
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.12
  eliud_generator: ^1.1.7
  lints: ^5.0.0
flutter:
  uses-material-design: true
